spring:
  datasource:
    url: jdbc:postgresql://192.168.1.20:5432/Insurance
  username: camunda_dev
  password: C@mu^d@D3v
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
zeebe:
  client:
    broker:
      gatewayAddress: 127.0.0.1:26500
    security:
      plaintext: true
